/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ChatTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CriticalAlerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "EmailService": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "GamesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "NotificationsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SettingsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "UsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}