/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ChatTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GamesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "NotificationsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SettingsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}